//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MentoHUST.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MENTOHUST_DIALOG            102
#define IDS_LINKURL                     102
#define IDS_CONTACT_TIP                 103
#define IDS_UPDATE_TIP                  104
#define IDS_CONTACT_TEXT                105
#define IDS_WELCOME                     106
#define IDS_MSG_CAPTION                 107
#define IDS_HELPERROR                   108
#define IDS_OUTPUT_D                    109
#define IDS_OUTPUT_U                    110
#define IDS_PACKAGE_FILTER              111
#define IDS_EXIT_CONFIRM                112
#define IDS_CFG_ACCOUNT                 113
#define IDS_CFG_PARAMETER               114
#define IDS_SAVE_SUCCESS                115
#define IDS_USERNAME                    116
#define IDS_PASSWORD                    117
#define IDS_IPADDRESS                   118
#define IDS_ACCOUNT_EMPTY               119
#define IDS_RESTART                     120
#define IDS_WRITE_ERROR                 121
#define IDS_SETRUN_ERROR                122
#define IDS_MSGCLEAR                    123
#define IDS_TRAY_CAPTION                124
#define IDS_TRAY_DISCONNECT             125
#define IDS_TRAY_START                  126
#define IDS_TRAY_USERNAME               127
#define IDR_MAINFRAME                   128
#define IDS_TRAY_PASSWORD               128
#define IDS_TRAY_SUCCESS                129
#define IDI_CERTTING                    129
#define IDS_TRAY_DHCP                   130
#define IDI_FAILED                      130
#define IDB_LOGO                        131
#define IDS_STATE_START                 131
#define IDD_CONFIGBOX                   132
#define IDS_STATE_USERNAME              132
#define IDD_CFG_ACCOUNT                 133
#define IDS_STATE_PASSWORD              133
#define IDD_CFG_PARAMETER               134
#define IDS_STATE_SUCCESS               134
#define IDC_CR_HAND                     135
#define IDS_DHCP_START                  135
#define IDS_DHCP_END                    136
#define IDR_TRAY_MENU                   136
#define IDS_STATE_DISCONNECT            138
#define IDS_RUIJIE_REG                  139
#define IDS_FIND_NONIC                  140
#define IDS_GET_ERROR                   141
#define IDS_ADDRESS_ERROR               142
#define IDS_OPEN_ERROR                  143
#define IDS_FILTER_ERROR                144
#define IDS_LOCALMAC                    145
#define IDS_LOCALIP                     146
#define IDS_BANDIP                      147
#define IDS_LOCALMASK                   148
#define IDS_LOCALGATE                   149
#define IDS_LOCALDNS                    150
#define IDS_PACKAGE_ERROR               151
#define IDS_CATCH_ERROR                 152
#define IDS_DISCONNECT                  153
#define IDS_BN_DISCONNECT               154
#define IDS_BN_CONNECT                  155
#define IDS_RUIJIE_VERSION              156
#define IDS_NO_CLIENTCHECK              157
#define IDS_MD5_STRING                  158
#define IDS_START_ERROR                 159
#define IDS_USER_ERROR                  160
#define IDS_PASS_ERROR                  161
#define IDS_SEND_ERROR                  162
#define IDS_SERVMAC                     163
#define IDS_CERT_DOWN                   164
#define IDS_CERT_FAILED                 165
#define IDS_GATEMAC                     166
#define IDS_ARP_ALERT                   167
#define IDS_SERVMSG1                    168
#define IDS_SERVMSG2                    169
#define IDS_WAIT_ERROR                  170
#define IDC_SC_LOGO                     1000
#define IDC_BN_OUTPUT                   1001
#define IDC_BN_OPTION                   1002
#define IDC_BN_ABOUT                    1003
#define IDC_BN_HELP                     1004
#define IDC_BN_CLEAR                    1005
#define IDC_CB_ACCOUNT                  1006
#define IDC_CB_ADAPTER                  1007
#define IDC_SC_STATE                    1008
#define IDC_ED_OUTPUT                   1009
#define IDC_SC_CONTRACT                 1010
#define IDC_SC_CHECKNEW                 1011
#define IDC_TAB                         1012
#define IDC_ED_USERNAME                 1013
#define IDC_ED_PASSWORD                 1014
#define IDC_IPADDRESS                   1015
#define IDC_BN_ADD                      1016
#define IDC_BN_DEL                      1017
#define IDC_LS_ACCOUNT                  1018
#define IDC_CK_AUTORUN                  1019
#define IDC_CK_AUTOCERT                 1020
#define IDC_CK_AUTOMIN                  1021
#define IDC_CK_BANDMAC                  1022
#define IDC_CB_STARTMODE                1023
#define IDC_CB_DHCPMODE                 1024
#define IDC_ED_TIMEOUT                  1025
#define IDC_ED_ECHOTIME                 1026
#define IDC_CK_PACKAGE                  1027
#define IDC_BN_BROWSER                  1028
#define IDC_ED_PATH                     1029
#define IDC_ED_RECONNECT                1030
#define ID_MENU_RESTORE                 32771
#define ID_MENU_CONNECT                 32772
#define ID_MENU_CONFIG                  32773
#define ID_MENU_HELP                    32774
#define ID_MENU_ABOUT                   32775
#define ID_MENU_EXIT                    32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
